from scouting.models import Player

SAMPLE_PLAYERS = [
    {
        'name': 'Victor Wanyama',
        'position': Player.Position.MIDFIELDER,
        'age': 33,
        'club': 'CF Montréal',
        'nationality': 'Kenyan',
        'region': Player.Region.NAIROBI,
        'rating': 82,
        'x_g': 0.12,
        'x_a': 0.08,
        'matches_played': 28,
        'goals': 3,
        'assists': 2,
    },
    {
        'name': 'Michael Olunga',
        'position': Player.Position.FORWARD,
        'age': 30,
        'club': 'Al-Duhail SC',
        'nationality': 'Kenyan',
        'region': Player.Region.NYANZA,
        'rating': 84,
        'x_g': 0.68,
        'x_a': 0.11,
        'matches_played': 32,
        'goals': 24,
        'assists': 5,
    },
    {
        'name': 'Joseph Okumu',
        'position': Player.Position.DEFENDER,
        'age': 27,
        'club': 'Reims',
        'nationality': 'Kenyan',
        'region': Player.Region.WESTERN,
        'rating': 79,
        'x_g': 0.04,
        'x_a': 0.03,
        'matches_played': 26,
        'goals': 1,
        'assists': 1,
    },
    {
        'name': 'Eric Ouma',
        'position': Player.Position.MIDFIELDER,
        'age': 25,
        'club': 'AIK',
        'nationality': 'Kenyan',
        'region': Player.Region.RIFT_VALLEY,
        'rating': 76,
        'x_g': 0.09,
        'x_a': 0.14,
        'matches_played': 30,
        'goals': 2,
        'assists': 7,
    },
]
